version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express_server
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mongodb # Указывает, что MongoDB должен быть запущен перед сервером
    networks:
      - app_network

  app:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - app_network

  mongodb:
    image: 'mongo:latest'
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example_password
    networks:
      - app_network

volumes:
  mongodb_data:

networks:
  app_network:
