version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express_server
    restart: always
    env_file:
      - .env
    ports:
      - "${EXPRESS_PORT}:${EXPRESS_PORT}"
    depends_on:
      - mongodb
    networks:
      - internal

  app:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - internal

  mongodb:
    container_name: ${MONGO_HOST}
    image: mongo
    restart: always
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - mongodb_data:/data/db
    networks:
      - internal

volumes:
  mongodb_data:

networks:
  internal:
